export enum Role {
    OWNER = 'owner',
    ADMIN = 'admin',
    BRANCH_MANAGER = 'branch-manager',
    STAFF ='staff',
}

const PERMISSIONS = {

    // BUSINESS LEVEL
    CREATE_BUSINESS: "create_business",
    DELETE_BUSINESS: 'delete_business',
    VIEW_ALL_BUSINESSES: 'view_all_businesses',
    MANAGE_BUSINESS_SETTINGS: 'manage_business_settings',

    // Staff/User Management
    ADD_STAFF: 'add_staff',
    REMOVE_STAFF: 'remove_staff',
    ASSIGN_ROLES: 'assign_roles',
    
    // Branch Level
    CREATE_BRANCH: 'create_branch',
    DELETE_BRANCH: 'delete_branch',
    VIEW_ALL_BRANCHES: 'view_all_branches',
    VIEW_ASSIGNED_BRANCH: 'view_assigned_branch',
    MANAGE_BRANCH_SETTINGS: 'manage_branch_settings',
    
    // Financial
    APPROVE_WITHDRAWALS: 'approve_withdrawals',
    VIEW_ALL_TRANSACTIONS: 'view_all_transactions',
    VIEW_BRANCH_TRANSACTIONS: 'view_branch_transactions',
    PROCESS_TRANSACTIONS: 'process_transactions',
    
    // Analytics
    VIEW_BUSINESS_ANALYTICS: 'view_business_analytics',
    VIEW_BRANCH_ANALYTICS: 'view_branch_analytics'
}

export const ROLE_HIERARCHY = {
    [Role.OWNER]: 5,
    [Role.ADMIN]: 4,
    [Role.BRANCH_MANAGER]: 3,
    [Role.STAFF]: 2
};

// Permissions map for each role
export const ROLE_PERMISSIONS = {
  [Role.OWNER]: [
    PERMISSIONS.CREATE_BUSINESS,
    PERMISSIONS.DELETE_BUSINESS,
    PERMISSIONS.VIEW_ALL_BUSINESSES,
    PERMISSIONS.MANAGE_BUSINESS_SETTINGS,
    PERMISSIONS.ADD_STAFF,
    PERMISSIONS.REMOVE_STAFF,
    PERMISSIONS.ASSIGN_ROLES,
    PERMISSIONS.CREATE_BRANCH,
    PERMISSIONS.DELETE_BRANCH,
    PERMISSIONS.VIEW_ALL_BRANCHES,
    PERMISSIONS.MANAGE_BRANCH_SETTINGS,
    PERMISSIONS.APPROVE_WITHDRAWALS,
    PERMISSIONS.VIEW_ALL_TRANSACTIONS,
    PERMISSIONS.VIEW_BUSINESS_ANALYTICS,
    PERMISSIONS.VIEW_BRANCH_ANALYTICS
  ],
  [Role.ADMIN]: [
    PERMISSIONS.VIEW_ALL_BRANCHES,
    PERMISSIONS.MANAGE_BRANCH_SETTINGS,
    PERMISSIONS.ADD_STAFF,
    PERMISSIONS.ASSIGN_ROLES,
    PERMISSIONS.APPROVE_WITHDRAWALS,
    PERMISSIONS.VIEW_ALL_TRANSACTIONS,
    PERMISSIONS.VIEW_BUSINESS_ANALYTICS,
    PERMISSIONS.VIEW_BRANCH_ANALYTICS
  ],
  [Role.BRANCH_MANAGER]: [
    PERMISSIONS.VIEW_ASSIGNED_BRANCH,
    PERMISSIONS.MANAGE_BRANCH_SETTINGS,
    PERMISSIONS.ADD_STAFF,
    PERMISSIONS.VIEW_BRANCH_TRANSACTIONS,
    PERMISSIONS.VIEW_BRANCH_ANALYTICS,
    PERMISSIONS.PROCESS_TRANSACTIONS
  ],
  [Role.STAFF]: [
    PERMISSIONS.VIEW_ASSIGNED_BRANCH,
    PERMISSIONS.PROCESS_TRANSACTIONS,
    PERMISSIONS.VIEW_BRANCH_TRANSACTIONS
  ]
};

